// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe82D2KJ2zAaXYqhX-PiJraEKttBPvJ8g',
    appId: '1:190883304174:web:437eb70f0af764035e99ff',
    messagingSenderId: '190883304174',
    projectId: 'proj1-e49dc',
    authDomain: 'proj1-e49dc.firebaseapp.com',
    databaseURL: 'https://proj1-e49dc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'proj1-e49dc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXlJUp6ehUfmQM5RgSoJDmn5kXLk94w8s',
    appId: '1:190883304174:android:54b2a575ef5d69fd5e99ff',
    messagingSenderId: '190883304174',
    projectId: 'proj1-e49dc',
    databaseURL: 'https://proj1-e49dc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'proj1-e49dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEGmbdH2hygEWXB5FfT2t-uXd7fbdWISc',
    appId: '1:190883304174:ios:343828a427feecef5e99ff',
    messagingSenderId: '190883304174',
    projectId: 'proj1-e49dc',
    databaseURL: 'https://proj1-e49dc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'proj1-e49dc.appspot.com',
    iosBundleId: 'com.example.ledController',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEGmbdH2hygEWXB5FfT2t-uXd7fbdWISc',
    appId: '1:190883304174:ios:be929b310d10ef705e99ff',
    messagingSenderId: '190883304174',
    projectId: 'proj1-e49dc',
    databaseURL: 'https://proj1-e49dc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'proj1-e49dc.appspot.com',
    iosBundleId: 'com.example.ledController.RunnerTests',
  );
}
